import type { ProviderDefinition } from './providers';

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    id: 'ollama',
    name: 'Ollama',
    description: 'Local LLM server',
    category: 'local',
    models: [],
    defaultModel: 'llama3.2',
    defaultEndpoint: 'http://localhost:11434',
    needsEndpoint: true,
    website: 'https://ollama.ai',
    needsApiKey: false,
    color: '#ff6b35',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'OpenAI cloud API',
    category: 'cloud',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4.1', 'gpt-4.1-mini', 'gpt-4.1-nano', 'o3', 'o4-mini'],
    defaultModel: 'gpt-4o',
    defaultEndpoint: 'https://api.openai.com/v1',
    needsEndpoint: false,
    website: 'https://openai.com',
    needsApiKey: true,
    color: '#00a67e',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Anthropic Claude API',
    category: 'cloud',
    models: ['claude-sonnet-4-20250514', 'claude-sonnet-4', 'claude-haiku-3-5-20241022', 'claude-opus-4-20250514'],
    defaultModel: 'claude-sonnet-4-20250514',
    defaultEndpoint: 'https://api.anthropic.com',
    needsEndpoint: false,
    website: 'https://anthropic.com',
    needsApiKey: true,
    color: '#d4a574',
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'Fast inference, free tier available',
    category: 'cloud',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
    defaultModel: 'llama-3.3-70b-versatile',
    defaultEndpoint: 'https://api.groq.com/openai/v1',
    needsEndpoint: false,
    website: 'https://console.groq.com/keys',
    needsApiKey: true,
    color: '#f55036',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'Strong reasoning capabilities, very cost-effective',
    category: 'cloud',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    defaultModel: 'deepseek-chat',
    defaultEndpoint: 'https://api.deepseek.com',
    needsEndpoint: false,
    website: 'https://platform.deepseek.com/api_keys',
    needsApiKey: true,
    color: '#4f6bf2',
  },
  {
    id: 'together',
    name: 'Together AI',
    description: 'Hosted open-source models',
    category: 'cloud',
    models: [
      'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
      'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
      'mistralai/Mixtral-8x7B-Instruct-v0.1',
    ],
    defaultModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
    defaultEndpoint: 'https://api.together.xyz/v1',
    needsEndpoint: false,
    website: 'https://api.together.xyz/settings/api-keys',
    needsApiKey: true,
    color: '#ff6b35',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    description: 'Fast model inference platform',
    category: 'cloud',
    models: [
      'accounts/fireworks/models/llama-v3p1-70b-instruct',
      'accounts/fireworks/models/llama-v3p1-8b-instruct',
      'accounts/fireworks/models/mixtral-8x7b-instruct',
    ],
    defaultModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    defaultEndpoint: 'https://api.fireworks.ai/inference/v1',
    needsEndpoint: false,
    website: 'https://fireworks.ai/account/api-keys',
    needsApiKey: true,
    color: '#ff4500',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'AI search with citations',
    category: 'cloud',
    models: ['sonar-pro', 'sonar', 'llama-3.1-sonar-large-128k-online'],
    defaultModel: 'sonar-pro',
    defaultEndpoint: 'https://api.perplexity.ai',
    needsEndpoint: false,
    website: 'https://www.perplexity.ai/settings/api',
    needsApiKey: true,
    color: '#36d399',
  },
  {
    id: 'xai',
    name: 'xAI/Grok',
    description: 'Grok models by xAI',
    category: 'cloud',
    models: ['grok-2', 'grok-2-vision'],
    defaultModel: 'grok-2',
    defaultEndpoint: 'https://api.x.ai/v1',
    needsEndpoint: false,
    website: 'https://console.x.ai/',
    needsApiKey: true,
    color: '#1d9bf0',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Powerful open and commercial models',
    category: 'cloud',
    models: ['mistral-large-latest', 'mistral-small-latest', 'codestral-latest', 'ministral-3b-latest'],
    defaultModel: 'mistral-large-latest',
    defaultEndpoint: 'https://api.mistral.ai/v1',
    needsEndpoint: false,
    needsApiKey: true,
    website: 'https://console.mistral.ai/api-keys/',
    color: '#ff6b35',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    description: "Google's Gemini models",
    category: 'cloud',
    models: ['gemini-2.0-flash', 'gemini-2.0-flash-lite', 'gemini-1.5-pro', 'gemini-1.5-flash'],
    defaultModel: 'gemini-2.0-flash',
    defaultEndpoint: 'https://generativelanguage.googleapis.com/v1beta',
    needsEndpoint: false,
    needsApiKey: true,
    website: 'https://aistudio.google.com/app/apikey',
    color: '#4285f4',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Enterprise NLP platform',
    category: 'cloud',
    models: ['command-r-plus', 'command-r', 'command-light'],
    defaultModel: 'command-r-plus',
    defaultEndpoint: 'https://api.cohere.com/v2',
    needsEndpoint: false,
    needsApiKey: true,
    website: 'https://dashboard.cohere.com/api-keys',
    color: '#39594d',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'One API key for all models',
    category: 'router',
    models: [
      'openai/gpt-4o',
      'anthropic/claude-sonnet-4',
      'meta-llama/llama-3.3-70b-instruct',
      'google/gemini-2.0-flash-001',
      'deepseek/deepseek-chat',
      'mistralai/mistral-large-latest',
      'xai/grok-2',
    ],
    defaultModel: 'openai/gpt-4o',
    defaultEndpoint: 'https://openrouter.ai/api/v1',
    needsEndpoint: false,
    needsApiKey: true,
    website: 'https://openrouter.ai/keys',
    color: '#8b5cf6',
  },
];

export function getProviderDefinition(id: string): ProviderDefinition | undefined {
  return PROVIDER_DEFINITIONS.find((p) => p.id === id);
}
